INSERT INTO `db_prod`.`categorias` (`titulo`, `cantidad`, `url_imagen`)
VALUES 
    ("Hoteles", 21, "https://images.unsplash.com/photo-1629140727571-9b5c6f6267b4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=327&q=80"),
    ("Hostel", 13, "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80"),
    ("Departamento", 7, "https://images.unsplash.com/photo-1603003568133-55b07aaf1860?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80"),
    ("Bed and breakfast", 6, "https://images.unsplash.com/photo-1642612373999-48d0098a9414?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y2FiYSVDMyVCMWFzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60");

INSERT INTO `db_prod`.`ciudades` (`nombre`, `pais`, `lat`, `lgn`, `imagen_url`)
VALUES 
    ("Mar del plata", "Buenos Aires", "-38.00042", "-57.5562", "https://fotos.perfil.com/2022/02/09/trim/950/534/mar-del-plata-20220209-1310706.jpg"),
    ("Villa General Belgrano", "Cordoba", "-31.97828", "-64.55627", "https://cdn0.casamientos.com.ar/article/5569/3_2/960/jpg/19655-arquitectura-centroeuropea-02.jpeg"),
    ("San Carlos de Bariloche", "Rio Negro", "-41.14557", "-71.30822", "https://www.moon.com/wp-content/uploads/2019/01/Argentina_Bariloche_Elijah-Lovkoff-iStock-820824654.jpg?fit=1080%2C1080"),
    ("Ushuaia", "Argentina", "-54.81084", "-68.31591", "https://pasaportenomada.es/wp-content/uploads/2022/03/que-ver-y-que-hacer-en-ushuaia-guia-para-visitar-la-ciudad.jpg"),
    ("Iruya", "Jujuy", "-22.79189", "-65.21703", "https://us.cdn.eltribuno.com/122016/1486939488718.jpg");

INSERT INTO `db_prod`.`caracteristicas` (`name`, `icono`)
VALUES
    ("WiFi", "FaWifi"), 
    ("Pileta", "FaSwimmingPool"),
    ("Spa", "FaHotTub"),
    ("Estacionamiento", "FaCarSide"),
    ("Aire acondicionado", "FaSnowflake"),
    ("Desayuno", "FaBreadSlice"),
    ("Servicio de limpieza", "FaBroom");

INSERT INTO `db_prod`.`productos` (`name`, `descripcion`, `puntuacion`, `ciudades_id`, `categorias_id`)
VALUES
    ("Blackstone Country Villages", "Con una piscina cubierta y muchas otras instalaciones recreativas a tu disposición, no te quedará ni un minuto libre. Tienes también una terraza y un jardín donde sentarte a contemplar el paisaje. Otros servicios de este apart-hotel incluyen acceso a internet por wifi gratuito, servicios de concierge y un lobby con chimenea.En Blackstone Country Villages tienes un snack bar a tu disposición. Todos los días, de 08:30 a 09:30, se sirve un desayuno para llevar con cargo.Tendrás servicio de recepción las 24 horas, resguardo de equipaje y caja de seguridad en la recepción a tu disposición. Hay un estacionamiento gratis disponible.Reserva una de las 48 habitaciones climatizadas, todas equipadas con kitchenette con un refrigerador/freezer tamaño grande y microondas. Mantén el contacto con los tuyos gracias al acceso a internet por wifi de cortesía. Las comodidades incluyen minibar, además de un servicio de limpieza disponible todos los días.Las distancias se muestran en números redondeados. Plaza Cervecera: 4,5 km Casa de la Historia y la Cultura del Bicentenario: 4,8 km Ayuntamiento de Villa General Belgrano: 4,9 km Iglesia de Santa Rosa: 15,7 km Reserva natural La Cascada: 17,9 km Villa Rumipal: 32,4 km Rio Subterraneo de la Cumbrecita: 34,4 km Estancia Alta Gracia: 47,9 km Museo Estancia Jesuitica y casa del Virrey Liniers: 48,6 km Museo Manuel de Falla: 49,3 km Club de golf Alta Gracia: 49,3 km Museo del Che Guevara: 49,3 km Con una ubicación estratégica en Villa General Belgrano, Blackstone Country Villages se encuentra a cinco minutos en auto de Plaza Cervecera y Casa de la Historia y la Cultura del Bicentenario. Hospédate en este apart-hotel y estarás a 17,9 km de Reserva natural La Cascada, así como a 49,3 km de Museo del Che Guevara.En Villa General Belgrano
    ", 4.2, 1, 1),
    ("Howard Johnson Inn Villa General Belgrano", "Para un relax sin igual, nada como una visita al spa, que ofrece masajes, tratamientos corporales y tratamientos faciales. Después de mejorar tu swing en el campo de golf, la diversión continúa gracias a las instalaciones recreativas, que incluyen una piscina cubierta y una cancha de tenis exterior. Se ofrece además acceso a internet por wifi gratuito, servicios de concierge y un lobby con chimenea.Azkaine, un restaurante con especialidad en cocina internacional, sirve almuerzos y cenas, aunque también puedes aprovechar el servicio a la habitación disponible con horario limitado cuando quieras quedarte en cama a descansar. Disfruta de tu bebida favorita en el Bar. Todos los días, de 07:30 a 10:30, se sirve un desayuno buffet gratuito.Tendrás centro de negocios, servicio de tintorería/lavandería y servicio de recepción las 24 horas a tu disposición. Por un cargo menor, podrás aprovechar distintos beneficios, como traslado al aeropuerto (ida y vuelta) con cargo y estacionamiento gratis.Te sentirás como en tu propia casa en una de las 46 habitaciones con minibar y televisión LCD. El acceso a internet por wifi de cortesía te mantendrá en contacto con los tuyos; también podrás ver tu programa favorito en la televisión con canales por cable. El baño privado con bañera con ducha dispone de artículos de tocador gratuitos y batas. Las comodidades incluyen caja de seguridad, escritorio y teléfono.Las distancias se muestran en números redondeados. Ayuntamiento de Villa General Belgrano: 2,3 km Casa de la Historia y la Cultura del Bicentenario: 2,6 km Plaza Cervecera: 2,7 km Iglesia de Santa Rosa: 9 km Reserva natural La Cascada: 11,2 km Villa Rumipal: 26,3 km Rio Subterraneo de la Cumbrecita: 41,4 km Estancia Alta Gracia: 50 km Museo Estancia Jesuitica y casa del Virrey Liniers: 50,5 km Museo Manuel de Falla: 51,7 km Club de golf Alta Gracia: 51,7 km Museo del Che Guevara: 51,7 km El aeropuerto más conveniente para llegar a Howard Johnson Inn Villa General Belgrano es Córdoba (COR-A. Internacional Ingeniero Aeronáutico Ambrosio L.V. Taravella) a 100 kmCon una conveniente ubicación en Villa General Belgrano, Howard Johnson Inn Villa General Belgrano ofrece unas vacaciones inolvidables en el campo, a cinco minutos en auto de Plaza Cervecera y Casa de la Historia y la Cultura del Bicentenario. Hospédate en este hotel de 4 estrellas y estarás a 11,2 km de Reserva natural La Cascada y a 51,7 km de Museo del Che Guevara.Cerca de Ayuntamiento de Villa General Belgrano
    ", 4.9, 1, 1),
    ("Boden Hotel", "Para un relax sin igual, nada como una visita al spa, que ofrece masajes. La diversión está asegurada en esta propiedad, que ofrece una piscina cubierta y piscina al aire libre de temporada. Otros servicios de este hotel incluyen acceso a internet por wifi gratuito y servicios de concierge.En Böden Hotel tienes un restaurante a tu disposición para comer algo. Todos los días se sirve un desayuno buffet gratuito.Tendrás servicio de tintorería/lavandería, servicio de recepción las 24 horas y resguardo de equipaje a tu disposición. Hay un estacionamiento gratis disponible.Te sentirás como en tu propia casa en una de las 70 habitaciones con decoración personalizada, que cuentan con minibar y Smart TV. El acceso a internet por wifi de cortesía te mantendrá en contacto con los tuyos; también podrás ver tu programa favorito en la televisión con canales por cable. El baño privado con ducha dispone de cabezal de ducha tipo lluvia y artículos de tocador gratuitos. Las comodidades incluyen caja de seguridad (con espacio para laptop) y escritorio, además de un servicio de limpieza disponible todos los días.Las distancias se muestran en números redondeados. Plaza Cervecera: 1,5 km Casa de la Historia y la Cultura del Bicentenario: 1,7 km Ayuntamiento de Villa General Belgrano: 1,8 km Iglesia de Santa Rosa: 12,6 km Reserva natural La Cascada: 14,8 km Villa Rumipal: 29,3 km Rio Subterraneo de la Cumbrecita: 37,3 km Estancia Alta Gracia: 49 km Museo Estancia Jesuitica y casa del Virrey Liniers: 49,6 km Museo Manuel de Falla: 50,3 km Club de golf Alta Gracia: 50,3 km Museo del Che Guevara: 50,4 km Al reservar tu estadía en Böden Hotel, en Villa General Belgrano, te encontrarás a cinco minutos en auto de Plaza Cervecera y Casa de la Historia y la Cultura del Bicentenario. Hospédate en este hotel de 4 estrellas y estarás a 14,8 km de Reserva natural La Cascada y a 50,4 km de Museo del Che Guevara.Cerca de Plaza Cervecera
    ", 3.8, 1, 4),
    ("Hotel Antiguo Camino", "Olvídate del estrés con los masajes, tratamientos corporales y tratamientos faciales disponibles. Otros servicios de este hotel incluyen acceso a internet por wifi gratuito, servicios de concierge y tiendas en la propiedad.En Hotel Antiguo Camino tienes un snack bar a tu disposición. Todos los días, de 08:30 a 12:00, se sirve un desayuno continental con cargo.Las siguientes instalaciones o servicios permanecerán sin abrir del 25 de Octubre de 2021 al 1 de Junio de 2022 (fechas sujetas a cambios): RestauranteTendrás personal multilingüe, resguardo de equipaje y lavandería a tu disposición. Por un cargo menor, podrás aprovechar distintos beneficios, como traslado al aeropuerto (ida y vuelta) con cargo y estacionamiento gratis.Te sentirás como en tu propia casa en una de las 10 habitaciones con decoración personalizada, que cuentan con minibar y televisión de pantalla plana. Mantén el contacto con los tuyos gracias al acceso a internet por wifi de cortesía. El baño privado con bañera o ducha dispone de cabezal de ducha tipo lluvia y artículos de tocador gratuitos. Las comodidades incluyen caja de seguridad y servicio nocturno de cortesía, además de un servicio de limpieza disponible todos los días.Las distancias se muestran en números redondeados. Ayuntamiento de Villa General Belgrano: 0,9 km Casa de la Historia y la Cultura del Bicentenario: 1,2 km Plaza Cervecera: 1,2 km Iglesia de Santa Rosa: 10,1 km Reserva natural La Cascada: 12,4 km Villa Rumipal: 27,4 km Rio Subterraneo de la Cumbrecita: 40 km Estancia Alta Gracia: 49,7 km Museo Estancia Jesuitica y casa del Virrey Liniers: 50,2 km Museo Manuel de Falla: 51,3 km Club de golf Alta Gracia: 51,3 km Museo del Che Guevara: 51,4 km Si reservas tu estadía en Hotel Antiguo Camino, en Villa General Belgrano, te encontrarás a 31,9 mi (51,4 km) de Museo del Che Guevara. Hospédate en este hotel y estarás a 12,4 km de Reserva natural La Cascada, así como a 0,9 km de Ayuntamiento de Villa General Belgrano.Cerca de Ayuntamiento de Villa General Belgrano
    ", 3.3, 1, 1),
    ("Ayres Del Champaqui Suites Golf & Spa", "", 3.9, 1, 1),
    ("Edelweiss", "", 3.6, 1, 4),
    ("Chamonix Posada", "Chamonix Posada & Spa cuenta con un jardín con piscina, un gimnasio y piscina climatizada cubierta. Ofrece habitaciones con conexión Wi-Fi gratuita y desayuno y se encuentra en la localidad de Villa General Belgrano. El establecimiento alberga un restaurante y una pista de tenis. La plaza mayor se halla a 1 km.

    Las 19 habitaciones del Chamonix se ubican en casas de madera de estilo alpino. Cuentan con suelo de parqué y grandes ventanas. Todas están equipadas con calefacción, aire acondicionado y TV por cable.

    Todos los días se sirve un desayuno buffet. En el restaurante podrá degustar cocina internacional a precios razonables.

    Las instalaciones del spa incluyen una bañera de hidromasaje, un sauna y un gimnasio. Los huéspedes pueden relajarse en el jardín o jugar un partido de tenis en las pistas del establecimiento.

    Chamonix Posada & Spa está a 6 km del río y a 90 km del aeropuerto internacional de Pajas Blancas.
    ", 3.3, 1, 1),
    ("Posada De Campo", "Posada De Campo, en Villa General Belgrano, es un lugar cálido, de ambientes acogedores donde se respira tranquilidad y cordialidad.

    Posee habitaciones dobles, triples, cuádruples y departamento de dos dormitorios con capacidad para 6 personas. Cuentan con aire acondicionado frió/calor, duchas de alta presión, tv led, frigobar, caja de seguridad, ventilador de techo y wifi en todo el predio. Además de contar con amplios espacios comunes ambientados con piezas únicas obtenidas de zonas rurales y restauradas en sus propias instalaciones. Sala con tv led, dvd. Biblioteca con ejemplares de diversos géneros literarios. Hogar a leña, salamandras, juegos de mesa, música ambiental, café y todo tipo de infusiones sin cargo. Cocheras cubiertas.

    El parque con 6000 metros que le permitirá aprovechar el aire libre junto a la pileta o a la sombra de algún árbol.

    Posee asadores móviles para colocar en el sitio que más les agrade para el almuerzo o cena familiar. Se facilita la vajilla necesaria para estos casos.

    Esperan contar con su presencia y no dude en esperar de ellos la mejor atención y una cálida bienvenida, deseando que su estadía se encuentre entre entre los mejores recuerdos….
    ", 3.1, 1, 1),
    ("Harmonie Hotel de Montaña", "Harmonie Hotel de Montaña se encuentra sobre la Ruta Provincial Nº 5, Km. 79, frente a la estación de servicio OIL. Se localiza a metros del segundo ingreso principal a Villa General Belgrano, al pie del Cerro de la Virgen y a solo cinco cuadras del centro, con la mejor vista a las Sierras Grandes.
    ", 3.9, 1, 1),
    ("Posada San Bras", "Con una piscina al aire libre y muchas otras instalaciones recreativas a tu disposición, no te quedará ni un minuto libre. Tienes también una terraza y un jardín donde sentarte a contemplar el paisaje. Esta posada también ofrece acceso a internet por wifi gratuito, servicios de concierge y un lobby con chimenea.En Posada San Bras tienes un restaurante a tu disposición para comer algo. Todos los días se sirve un desayuno con opciones de la cocina local gratuito.Tendrás servicio de recepción las 24 horas, personal multilingüe y resguardo de equipaje a tu disposición. Por un cargo menor, podrás aprovechar distintos beneficios, como traslado al aeropuerto (ida y vuelta) disponible las 24 horas y estacionamiento gratis.Te sentirás como en tu propia casa en una de las 8 habitaciones con aire acondicionado, refrigerador y microondas. Aprovecha la cocina compartida para preparar tus propias comidas. El acceso a internet por wifi de cortesía te mantendrá en contacto con los tuyos; también podrás ver tu programa favorito en la televisión con canales por cable. El baño privado con bañera y ducha independientes dispone de bañera de hidromasaje y cabezal de ducha tipo lluvia.Las distancias se muestran en números redondeados. Ayuntamiento de Villa General Belgrano: 1,1 km Casa de la Historia y la Cultura del Bicentenario: 1,3 km Plaza Cervecera: 1,6 km Iglesia de Santa Rosa: 10,9 km Reserva natural La Cascada: 13,1 km Villa Rumipal: 28,2 km Rio Subterraneo de la Cumbrecita: 40,2 km Estancia Alta Gracia: 50,2 km Museo Estancia Jesuitica y casa del Virrey Liniers: 50,9 km Museo Manuel de Falla: 51,6 km Club de golf Alta Gracia: 51,6 km Museo del Che Guevara: 51,6 km Al reservar tu estadía en Posada San Bras, en Villa General Belgrano, te encontrarás a cinco minutos en auto de Ayuntamiento de Villa General Belgrano y Plaza Cervecera. Hospédate en esta posada y estarás a 13,1 km de Reserva natural La Cascada, así como a 51,6 km de Museo del Che Guevara.Cerca de Ayuntamiento de Villa General Belgrano
    ", 3.2, 4, 1),
    ("Hotel Tirol D'Andrea", "Confort, comodidad: el lugar ideal para disfrutar de sus vacaciones en Villa General Belgrano.

    Ubicado en pleno centro, sobre la calle principal, en Hotel Tirol D’Andrea tendrá la comodidad de estar al alcance de todos los centros de interés y restaurantes de nuestro pueblo.

    Disfrutará de todos los servicios repartidos 3 niveles comunicados por un ascensor: planta baja con el lobby, restaurante & pileta. 1ª planta el Sector Moderno, totalmente reformado y equipado. 2ª planta sector Alpino. Todo ello, con la calidad de una atención familiar.
    ", 3.2, 1, 4),
    ("Atelier De Charme", "Atelier Hotel de Charme se encuentra en Villa General Belgrano y pone especial cuidado en los detalles, decoración, servicio, productos caseros para el desayuno, calidad de atención, para que tenga una estadía placentera, calidad y genuina. Ubicado a 100 metros de la calle principal, sobre un parque arbolado de más de 3.000m2 que desemboca al arroyo, en Atelier Hotel de Charme, encontrara cercanía y tranquilidad.
    ", 3.1, 1, 1),
    ("Bad-Wiessee Apart", "Para un relax sin igual, nada como una visita al spa, que ofrece masajes, tratamientos corporales y tratamientos faciales. Si quieres divertirte, aquí tienes para elegir, con instalaciones recreativas como una piscina al aire libre, una piscina cubierta y sala de fitness. Este hotel también ofrece acceso a internet por wifi gratuito, servicios de concierge y un área de picnic.Todos los días, de 08:00 a 08:30, se sirve un desayuno completo gratuito.Tendrás servicio de tintorería/lavandería, resguardo de equipaje y lavandería a tu disposición. Por un cargo menor, podrás aprovechar distintos beneficios, como traslado al aeropuerto (ida y vuelta) con cargo y estacionamiento gratis.Te sentirás como en tu propia casa en una de las 14 habitaciones con aire acondicionado. Mantén el contacto con los tuyos gracias al acceso a internet por wifi de cortesía. El cuarto de baño dispone de ducha y artículos de tocador gratuitos. Las comodidades incluyen caja de seguridad y cortinas blackout, además de un servicio de limpieza disponible todos los días.Las distancias se muestran en números redondeados. Ayuntamiento de Villa General Belgrano: 1,2 km Plaza Cervecera: 1,5 km Casa de la Historia y la Cultura del Bicentenario: 1,6 km Iglesia de Santa Rosa: 9,7 km Reserva natural La Cascada: 11,9 km Villa Rumipal: 27 km Rio Subterraneo de la Cumbrecita: 40,6 km Estancia Alta Gracia: 49 km Museo Estancia Jesuitica y casa del Virrey Liniers: 49,7 km Museo Manuel de Falla: 50,4 km Club de golf Alta Gracia: 50,4 km Museo del Che Guevara: 50,4 km Al reservar tu estadía en Badwiessee Apart Hotel & Spa, en Villa General Belgrano, te encontrarás a cinco minutos en auto de Plaza Cervecera y Ayuntamiento de Villa General Belgrano. Hospédate en este hotel con spa y estarás a 11,9 km de Reserva natural La Cascada, así como a 50,4 km de Museo del Che Guevara.Cerca de Ayuntamiento de Villa General Belgrano
    ", 4.4, 1, 1),
    ("Chalet Suisse Posada y Spa", "", 4.2, 1, 1),
    ("Blumenau", "", 4.9, 1, 1),
    ("Cabanas Mirasoles", "", 4.4, 1, 1),
    ("Posada Del Centro", "", 4.4, 1, 1),
    ("La Posada De Akasha", "", 4.1, 1, 1),
    ("Calina Hotel - Casa De Huespedes", "", 4.8, 1, 1),
    ("Rancho Grande", "", 4.0, 1, 1),
    ("Grenouille", "", 4.8, 1, 1),
    ("Los Colibries", "", 4.5, 1, 1),
    ("Estancia Don Jose", "", 4.7, 1, 1),
    ("Alpinas Sol Y Lunas Vgb.", "", 4.6, 1, 1),
    ("NH Buenos Aires Florida", "El hotel NH Buenos Aires Florida de Buenos Aires y con 4 estrellas de categoría, tiene una ubicación ideal en el centro de los distritos de compras y financiero, lo que hace que sea el alojamiento ideal si deseas salir a disfrutar de la ciudad. Está ubicado junto al centro comercial de la calle Florida y también ofrece fácil acceso a los complejos de compras y entretenimiento Galerías Pacífico y Puerto Madero. Descubrirás que también es la base ideal para explorar las zonas históricas de la ciudad y para visitar monumentos famosos.
", 5.0, 2, 2),
    ("Sofitel Buenos Aires Recoleta", "", 5.0, 2, 2),
    ("NH Buenos Aires City", "El hotel de 5 estrellas NH Buenos Aires City, cuya llamativa fachada art decó data de los años 30, se encuentra en pleno centro histórico de Buenos Aires. Sus más de 300 habitaciones están insonorizadas, tienen suelos de parquet y ventanales que permiten la entrada de luz natural. Algunas poseen vistas a la ciudad, y se ofrecen habitaciones comunicadas para familias. El hotel alberga un gimnasio y una elegante piscina con solárium en la azotea, desde la que se pueden disfrutar de amplias vistas sobre el centro de Buenos Aires. También dispone de wifi gratuito en todo el hotel, salas para eventos, recepción 24 horas, lavandería y caja fuerte. El NH Buenos Aires City cuenta con un lobby-bar y un restaurante que ofrece buffet de desayuno y platos a la carta de especialidad argentina y española. El hotel se sitúa en el centro de la ciudad, a menos de cinco minutos de varios lugares emblemáticos como la Plaza de Mayo o la Casa Rosada.
", 5.0, 4, 2),
    ("Exe Hotel Colón", "", 5.0, 2, 4),
    ("NH Buenos Aires Florida", "El hotel NH Buenos Aires Florida de Buenos Aires y con 4 estrellas de categoría, tiene una ubicación ideal en el centro de los distritos de compras y financiero, lo que hace que sea el alojamiento ideal si deseas salir a disfrutar de la ciudad. Está ubicado junto al centro comercial de la calle Florida y también ofrece fácil acceso a los complejos de compras y entretenimiento Galerías Pacífico y Puerto Madero. Descubrirás que también es la base ideal para explorar las zonas históricas de la ciudad y para visitar monumentos famosos.
", 5.0, 2, 2),
    ("Hotel Mio Buenos Aires", "Situado en pleno corazón de Recoleta, una de las zonas más comerciales de la ciudad de Buenos Aires, se encuentra el Hotel Mio Buenos Aires, un alojamiento de 5 estrellas estilo boutique enfocado al turismo de negocios y de relajación. Las 30 habitaciones, de estilo vanguardista, muebles de diseño y luminosas, disponen de camas king size con sábanas italianas Frette y carta de almohadas, zona de descanso con sofás, estación de conexión para iPod, televisor con reproductor de DVD y minibar, así como baño privado con todo tipo de amenities. El Hotel Mio Buenos Aires cuenta con amplia zona de spa de lujo con tratamientos de estética y servicio de masajes, además de sauna, baño de vapor y bañera de hidromasaje. También cuenta con servicio de transporte al aeropuerto, gimnasio, biblioteca, terraza con solárium y servicio de recepción 24 horas. Se ofrece servicio de desayuno estilo buffet y servicio de habitaciones. El Teatro Colón se encuentran a poco más de 15 minutos a pie.
", 5.0, 2, 2),
    ("HTL 9 de Julio", "Situado en el corazón de la capital argentina, el HTL 9 de Julio permite al viajero alojarse en el microcentro porteño, a un paso de los rincones más emblemáticos de la localidad con mayor oferta cultural del Cono Sur. Dispone de 57 habitaciones, que se distribuyen en dos plantas: la inferior, destinada a sala de estar, y la superior, que ejerce de dormitorio. Todas ellas cuentan con aire acondicionado, televisor LCD, minibar, escritorio, caja fuerte y baño privado con ducha y secador de cabello. Entre sus servicios, el HTL 9 de Julio ofrece conexión wifi gratuita, recepción 24 horas, consigna de equipajes, conserje y lavandería. Las estancias cuentan con hervidor eléctrico, sirviéndose en las mismas cada mañana un desayuno completo. Asimismo, se halla a menos de diez minutos a pie del histórico Café Tortoni, emplazado en la avenida de Mayo. Desde el alojamiento se puede visitar el Obelisco, situado a tan solo diez minutos caminando, o la Casa Rosada, localizada a 15 minutos.
", 5.0, 2, 2),
    ("CasaSur Bellini Hotel", "Para un relax sin igual, nada como una visita al spa, que ofrece masajes, tratamientos corporales y tratamientos faciales. Si quieres divertirte, aquí tienes para elegir, con instalaciones recreativas como una piscina al aire libre, sauna y sala de fitness. Otros servicios de este hotel de estilo Art decó incluyen acceso a internet por wifi gratuito y servicios de concierge.Puedes probar una deliciosa comida en el restaurante Tora de este hotel o, cuando quieras quedarte a descansar, pedir algo del menú del servicio a la habitación disponible con horario limitado. Todos los días, de 07:00 a 11:00, se sirve un desayuno a la carta gratuito.Tendrás centro de negocios, periódicos gratuitos en el lobby y servicio de tintorería/lavandería a tu disposición.Te sentirás como en tu propia casa en una de las 79 habitaciones con decoración personalizada, que cuentan con minibar y cafetera expreso. Las camas cuentan con colchones con pillow-top, cubrecama y ropa de cama de alta calidad para descansar plácidamente. Las habitaciones disponen de balcón o patio. El acceso a internet por wifi de cortesía te permite comunicarte con los tuyos, y en tus ratos libres podrás entretenerte con la televisión LED de 42 pulgadas con canales digitales. El baño privado con ducha dispone de cabezal de ducha tipo lluvia y artículos de tocador gratuitos.Las distancias se muestran en números redondeados. Museo Evita: 0,2 km Jardín Botánico Carlos Thays: 0,3 km Bosques de Palermo: 0,5 km Parque Las Heras: 0,6 km Jardín Japonés: 0,6 km Palermo Soho: 0,7 km Ecoparque Interactivo de Buenos Aires: 0,9 km Plaza Italia: 1 km Centro de convenciones La Rural: 1,1 km Museo de Arte Latinoamericano de Buenos Aires: 1,2 km Avenida Santa Fe: 1,2 km Embajada de Estados Unidos de América: 1,3 km Museo Nacional de Arte Decorativo: 1,3 km Centro comercial Alto Palermo: 1,3 km Centro de convenciones La Rural: 1,3 km Aeropuertos más cercanos: Buenos Aires (EZE-A. Internacional Ministro Pistarini): 33,6 kmBuenos Aires (AEP-Aeroparque Jorge Newbery): 4,8 kmAeropuerto recomendado para CasaSur Bellini Hotel: Buenos Aires (EZE-A. Internacional Ministro Pistarini). Con una conveniente ubicación en la zona de CasaSur Bellini Hotel, en Buenos Aires, Palermo se encuentra a cinco minutos a pie de Museo Evita y Jardín Botánico Carlos Thays. Hospédate en este hotel de 4 estrellas y estarás a 1,1 km de Jardín Japonés, así como a 1,4 km de Museo de Arte Latinoamericano de Buenos Aires.A poca distancia de Jardín Japonés
", 5.0, 2, 2),
    ("Alvear Icon", "Relájate en el spa de servicio completo, que ofrece masajes, tratamientos corporales y tratamientos faciales. La diversión está asegurada en esta propiedad, que ofrece una bodega de vinos junto a la propiedad, un gimnasio y una piscina cubierta. Otros servicios de este hotel incluyen acceso a internet por wifi gratuito, servicios de concierge y un salón de baile. Recorre rápida y cómodamente los principales sitios de interés de la zona gracias al servicio de traslado (con cargo).Deleita tu paladar en Kayla Restaurant, uno de los 3 restaurantes de este hotel o, si prefieres, ordena algo del servicio a la habitación disponible las 24 horas. También, si se te antoja un snack, puedes pedirlo en 3 cafeterías. Relájate con un refresco del bar junto a la piscina o de uno de los 2 bares. Todos los días, de 07:00 a 11:00, se sirve un desayuno buffet con cargo.Tendrás acceso a internet por cable gratis, centro de negocios y servicio de tintorería/lavandería a tu disposición. Este hotel pone a tu disposición 6 salas de reuniones donde celebrar todo tipo de eventos. Por un cargo menor, podrás aprovechar distintos beneficios, como traslado al aeropuerto (ida y vuelta) disponible las 24 horas y un servicio de traslado desde/hacia la terminal de cruceros.Reserva una de las 159 habitaciones climatizadas, todas equipadas con bañera de hidromasaje y televisión LCD. Las camas cuentan con colchones con pillow-top, cubrecama y sábanas de algodón egipcio para descansar plácidamente. Para los momentos de entretenimiento, tienes una televisión con canales por cable y acceso a internet gratis por cable y wifi. El baño privado con bañera y ducha independientes está equipado con bañera de hidromasaje y artículos de tocador de diseño.Las distancias se muestran en números redondeados. Puente de la Mujer: 0,6 km Buque Museo Fragata Presidente Sarmiento: 0,8 km Convento Santo Domingo: 1 km Casa Rosada: 1,3 km Plaza de Mayo: 1,4 km Bolsa de Valores de Buenos Aires: 1,5 km Luna Park: 1,5 km Centro Cultural Kirchner: 1,5 km Colección de Arte Amalia Lacroze de Fortabat: 1,5 km Casa Mínima: 1,5 km Catedral Metropolitana de Buenos Aires: 1,6 km Puerto Madero Casino: 1,7 km Centro comercial Galería Güemes: 1,8 km Reserva ecológica Costanera Sur: 1,8 km Avenida 9 de Julio: 1,9 km Aeropuertos más cercanos: Buenos Aires (EZE-A. Internacional Ministro Pistarini): 33,6 kmBuenos Aires (AEP-Aeroparque Jorge Newbery): 10,1 kmAeropuerto recomendado para Alvear Icon Hotel: Buenos Aires (EZE-A. Internacional Ministro Pistarini). Al reservar tu estadía en Alvear Icon Hotel, tendrás una ubicación céntrica en Buenos Aires, a 10 minutos a pie de Puente de la Mujer y Buque Museo Fragata Presidente Sarmiento. Hospédate en este hotel de 5 estrellas y estarás a 1,8 km de Colección de Arte Amalia Lacroze de Fortabat, así como a 2 km de Puerto Madero Casino.A poca distancia de Plaza de Mayo
", 5.0, 4, 2),
    ("NH Buenos Aires 9 de Julio", "", 4.3, 2, 2),
    ("Grand Brizo", "", 4.3, 2, 2),
    ("Hotel Novotel Buenos Aires", "", 4.3, 2, 2),
    ("Palermo Bridge", "", 4.1, 2, 2),
    ("NH Buenos Aires Tango", "", 4.7, 2, 2),
    ("Tulip Inn São Paulo Paulista", "Descripción general: Facilidad de acceso a muchas atracciones locales., Muy cercano al distrito de compras, Diseñado para el viajero corporativo, Diseñado para satisfacer las necesidades de la familia, Alojamiento ideal para una escapada de vacaciones. Ubicación: Ubicado convenientemente en Sao Paulo. Recreación: Centro de fitness totalmente equipado. Restaurantes y salones: Restaurante propio, Bar y salón con servicios completos, Restaurante cercano. Servicios: Servicio en el mostrador de recepción las 24 horas, Ascensores, Servicios de limpieza a seco y lavandería con valet, Servicio limitado en la habitación. Instalaciones para reuniones: Instalaciones para banquetes, Centro de negocios totalmente equipado. Alojamiento: 96 habitaciones., Alojamiento 3 estrellas, Habitaciones estilo contemporáneo
", 4.5, 4, 3),
    ("Mercure São Paulo Paulista Hotel", "El Mercure São Paulo Paulista le ofrece una experiencia agradable y auténtica si lo que busca es alojarse cerca de la avenida Paulista. Sus acogedoras habitaciones son una opción excelente si viene a São Paulo en un viaje individual, en familia, de negocios u ocio. Los apartamentos están equipados con Smart TV, minibar, secador, escritorio y balcón opcional. Todas las habitaciones cuentan con aire acondicionado y WIFI.
", 4.2, 3, 3),
    ("DoubleTree by Hilton São Paulo Itaim", "Elige entre las distintas instalaciones recreativas, que incluyen una piscina al aire libre y sala de fitness. Se ofrece además acceso a internet por wifi gratuito y una televisión en las áreas comunes.Un sitio ideal para comer en este hotel es su restaurante, que además cuenta con un bar. Y, si no quieres salir, también puedes aprovechar el servicio a la habitación disponible las 24 horas. El desayuno buffet, con cargo adicional, se sirve de lunes a viernes de 06:00 a 10:00, mientras que los fines de semana el horario es de 06:30 a 11:00.Tendrás centro de negocios, servicio de tintorería/lavandería y servicio de recepción las 24 horas a tu disposición. Este hotel pone a tu disposición 8 salas de reuniones donde celebrar todo tipo de eventos.Te sentirás como en tu propia casa en una de las 131 habitaciones con aire acondicionado, minibar y televisión LED. Las habitaciones disponen de balcón. El acceso a internet por wifi de cortesía te mantendrá en contacto con los tuyos; también podrás ver tu programa favorito en la televisión con canales por cable. El cuarto de baño dispone de ducha, artículos de tocador gratuitos y secador de pelo.Las distancias se muestran en números redondeados. Museo de la casa brasileña: 0,9 km Museo brasileño de escultura: 1,5 km Centro Comercial JK Iguatemi: 1,7 km Club deportivo Pinheiros: 1,8 km Área comercial Avenida Engenheiro Luís Carlos Berrini: 2,4 km Calle Augusta: 2,5 km Parque de Ibirapuera: 2,6 km Parque Alfredo Volpi: 2,7 km Shopping Eldorado: 2,7 km Jockey Club: 2,8 km Calle Oscar Freire: 2,8 km Teatro del Renacimiento: 3,7 km Callejón de Batman: 3,7 km Shopping Ibirapuera: 3,7 km Museo de arte moderno de Sao Paulo: 3,8 km Aeropuertos más cercanos: São Paulo (GRU-Aeropuerto Internacional Guarulhos - Governador Andre Franco Montoro): 34 kmSão Paulo (CGH-Congonhas): 7,7 kmAeropuerto recomendado para DoubleTree by Hilton Sao Paulo Itaim: São Paulo (GRU-Aeropuerto Internacional Guarulhos - Governador Andre Franco Montoro). Al reservar tu estadía en DoubleTree by Hilton Sao Paulo Itaim, en la zona de Itaim Bibi, en Sao Paulo, te encontrarás a 4 minutos en auto de Parque de Ibirapuera y a 6 minutos en auto de Paulista Avenue. Hospédate en este hotel y estarás a 3 km de Calle Augusta, así como a 3,1 km de Shopping Eldorado.En Sao Paulo (Itaim Bibi)
", 4.9, 3, 3),
    ("Hotel Excelsior", "Aprovecha los prácticos servicios que se te ofrecen, como servicios de concierge o una televisión en las áreas comunes.En Hotel JBDelgado Plus Excelsior São Paulo by Monreale Hotels tienes un restaurante a tu disposición para comer algo. Y para darle el punto final a tu día de la mejor forma, tómate un refrescante cocktail en el Bar. Todos los días, de 06:00 a 10:00, se sirve un desayuno buffet gratuito.Las siguientes instalaciones o servicios permanecerán sin abrir del 1 de Enero de 2022 al 1 de Junio de 2022 (fechas sujetas a cambios): RestauranteTendrás centro de negocios, periódicos gratuitos en el lobby y servicio de recepción las 24 horas a tu disposición. Este hotel pone a tu disposición 6 salas de reuniones donde celebrar todo tipo de eventos. Hay un estacionamiento disponible.Te sentirás como en tu propia casa en una de las 198 habitaciones con aire acondicionado y televisión LCD. El acceso a internet por wifi de cortesía te mantendrá en contacto con los tuyos; también podrás ver tu programa favorito en la televisión con canales por cable. El cuarto de baño dispone de bañera con ducha y secador de pelo. Las comodidades incluyen caja de seguridad, escritorio y teléfono.Las distancias se muestran en números redondeados. Centro histórico: 0,1 km Plaza de la República: 0,1 km Edificio Itália: 0,4 km Teatro municipal de São Paulo: 0,5 km Edificio Copan: 0,6 km Plaza Arouche: 0,6 km Bolsa de Valores de Sao Paulo: 0,9 km Rua 25 de Marco: 1 km Hospital Central da Santa Casa de Misericórdia de São Paulo: 1,1 km Universidad presbiteriana de Mackenzie: 1,1 km Calle Augusta: 1,2 km Museo de la Lengua Portuguesa: 1,2 km Sala de conciertos Sala Sao Paulo: 1,3 km Catedral de Sao Paulo: 1,4 km Calle José Paulino: 1,5 km Aeropuertos más cercanos: São Paulo (GRU-Aeropuerto Internacional Guarulhos - Governador Andre Franco Montoro): 29,2 kmSão Paulo (CGH-Congonhas): 11,4 kmCampinas (VCP-A. Internacional de Viracopos - Campinas): 92,6 kmAl reservar tu estadía en Hotel JBDelgado Plus Excelsior São Paulo by Monreale Hotels, tendrás una ubicación céntrica en Sao Paulo, a 6-minutos a pie de Teatro municipal de São Paulo y a 12 minutos a pie de Rua 25 de Marco. Hospédate en este hotel y estarás a 2,4 km de Sala de conciertos Sala Sao Paulo, así como a 2,6 km de Plaza Liberty.En Sao Paulo (Zona centro)
", 4.6, 3, 3),
    ("Hotel Nobile Downtown São Paulo", "Aprovecha las instalaciones recreativas, que incluyen una piscina cubierta y sala de fitness. Otros servicios de este hotel incluyen acceso a internet por wifi gratuito, una televisión en las áreas comunes y un salón de fiestas.Cuando quieras almorzar o cenar, ve a Restaurante Downtown SP, un restaurante de este hotel, aunque también puedes llamar al servicio a la habitación disponible las 24 horas cuando no desees salir. Y para darle el punto final a tu día de la mejor forma, tómate un refrescante cocktail en el Bar. Todos los días, de 06:00 a 10:00, se sirve un desayuno buffet gratuito.Tendrás servicio de tintorería/lavandería, servicio de recepción las 24 horas y personal multilingüe a tu disposición. Hay un valet parking gratis disponible.Te sentirás como en tu propia casa en una de las 256 habitaciones con minibar y Smart TV. Para los momentos de entretenimiento, tienes una televisión con canales digitales y acceso a internet gratis por cable y wifi. El baño privado con ducha dispone de artículos de tocador gratuitos y secador de pelo. Las comodidades incluyen caja de seguridad, escritorio y teléfono.Las distancias se muestran en números redondeados. Centro histórico: 0,1 km Edificio Copan: 0,2 km Edificio Itália: 0,2 km Plaza de la República: 0,3 km Hospital Central da Santa Casa de Misericórdia de São Paulo: 0,6 km Universidad presbiteriana de Mackenzie: 0,7 km Plaza Arouche: 0,7 km Calle Augusta: 0,7 km Centro comercial Higienopolis: 1,5 km Centro comercial y de convenciones Frei Caneca: 1,5 km Bolsa de Valores de Sao Paulo: 1,5 km Rua 25 de Marco: 1,6 km Sala de conciertos Sala Sao Paulo: 1,7 km Catedral de Sao Paulo: 1,7 km Museo de la Lengua Portuguesa: 1,8 km Aeropuertos más cercanos: São Paulo (CGH-Congonhas): 11,3 kmSão Paulo (GRU-Aeropuerto Internacional Guarulhos - Governador Andre Franco Montoro): 27,6 kmAeropuerto recomendado para Nobile Downtown São Paulo: São Paulo (CGH-Congonhas). Si reservas tu estadía en Nobile Downtown São Paulo, tendrás una ubicación céntrica en Sao Paulo, a 4 minutos en auto de Paulista Avenue y a 5 minutos de Iglesia Mundial del Poder de Dios. Hospédate en este hotel y estarás a 1 km de Calle Augusta, así como a 1,1 km de Plaza de la República.En Sao Paulo (Zona centro)
", 4.1, 3, 3),
    ("Fortune Residence", "Para tus ratos libres, tienes instalaciones recreativas, como una piscina al aire libre, una piscina cubierta y baño turco, a tu disposición. Se ofrece además acceso a internet por wifi gratuito, una televisión en las áreas comunes y asistencia turística y para la compra de entradas.Prueba las especialidades de cocina brasileña en Vascello, buffet con un bar. O, cuando quieras seguir descansando, llama al servicio a la habitación disponible con horario limitado. Los fines de semana, de 06:30 a 10:30, se sirve un desayuno buffet con cargo.Tendrás periódicos gratuitos en el lobby, servicio de recepción las 24 horas y personal multilingüe a tu disposición.Reserva una de las 60 habitaciones con kitchenette y disfruta de una estadía inolvidable. Las habitaciones disponen de balcón. El acceso a internet por wifi de cortesía te permite comunicarte con los tuyos, y en tus ratos libres podrás entretenerte con la televisión LCD de 40 pulgadas con canales por cable. Las comodidades incluyen caja de seguridad y escritorio, además de un servicio de limpieza disponible todos los días.Las distancias se muestran en números redondeados. Calle Augusta: 0,1 km Teatro del Renacimiento: 0,2 km Paulista Avenue: 0,3 km Centro de Convenciones Reboucas: 0,7 km Calle Oscar Freire: 0,8 km Hospital Incor: 0,8 km Hospital clínico FMUSP: 1 km Museo de Arte de São Paulo: 1 km Hospital Nove de Julho: 1 km Centro comercial y de convenciones Frei Caneca: 1,4 km Hospital Sirio Libanés: 1,5 km Universidad presbiteriana de Mackenzie: 1,9 km Estadio de Pacaembú: 2,1 km Museo brasileño de escultura: 2,2 km Centro histórico: 2,4 km Aeropuertos más cercanos: São Paulo (GRU-Aeropuerto Internacional Guarulhos - Governador Andre Franco Montoro): 30,5 kmSão Paulo (CGH-Congonhas): 9,8 kmAeropuerto recomendado para H4 Fortune Jardins: São Paulo (GRU-Aeropuerto Internacional Guarulhos - Governador Andre Franco Montoro). Si reservas tu estadía en H4 Fortune Jardins, que se ubica en la zona de Jardins, en Sao Paulo, te encontrarás a 1 minutos en auto de Paulista Avenue y a 5 minutos en auto de Teatro municipal de São Paulo. Hospédate en este apart-hotel y estarás a 4 km de Plaza Liberty, así como a 5,6 km de Rua 25 de Marco.A poca distancia de Paulista Avenue
", 4.2, 3, 3),
    ("Pullman São Paulo Ibirapuera", "El moderno hotel Pullman São Paulo Ibirapuera está listo para darle la bienvenida. Las habitaciones son acogedoras, están insonorizadas y ofrecen opciones para personas con movilidad reducida, oficinas y plantas Executive con servicios exclusivos. Todas disponen de WIFI gratuito y aire acondicionado. Cuenta con restaurantes con platos variados y un menú moderno con cocina fusión, salas de eventos, piscina, gimnasio, sauna seca, spa Shishindo, centro de negocios y espacio infantil.
", 4.3, 5, 4),
    ("Blue Tree Towers Anália Franco", "Para tus ratos libres, tienes instalaciones recreativas, como una piscina al aire libre, sauna y sala de fitness, a tu disposición. Se ofrece además acceso a internet por wifi gratuito, una televisión en las áreas comunes y asistencia turística y para la compra de entradas.Pide una mesa en Gastronomia Albuquerque, un restaurante con especialidad en cocina internacional y disponible para almuerzos, cenas o brunch. Si no se te antoja salir, también puedes llamar al servicio a la habitación disponible las 24 horas. Y para darle el punto final a tu día de la mejor forma, tómate un refrescante cocktail en el Bar. Todos los días, de 06:30 a 10:00, se sirve un desayuno buffet gratuito.Tendrás check-in exprés, servicio de recepción las 24 horas y resguardo de equipaje a tu disposición. ¿Estás organizando un evento en Sao Paulo? En este hotel, dispones de 107 metros cuadrados de espacio con zonas para conferencias.Te sentirás como en tu propia casa en una de las 126 habitaciones con minibar y televisión LCD. En tus ratos libres, tendrás una televisión con canales por cable para entretenerte. Las comodidades incluyen caja de seguridad, además de un servicio de limpieza disponible previa solicitud.Las distancias se muestran en números redondeados. Parque deportivo Parque Esportivo dos Trabalhadores: 0,1 km Southern Cross University: 0,6 km Centro comercial Analia Franco: 0,7 km Hospital e Maternidade Vitória: 0,8 km Hospital e Maternidade São Luiz Unidade Anália Franco: 1,4 km Centro comercial Metro Boulevard Tatuapé: 3,8 km Templo de Salomón: 7,3 km Museo de la Inmigración: 7,3 km Centro histórico: 7,7 km Museo Paulista: 7,9 km Iglesia Mundial del Poder de Dios: 8,1 km Centro comercial Aricanduva: 8,5 km Centro comercial Feirinha da Madrugada: 8,8 km Centro comercial Shopping 25 Brás: 9,3 km Shopping Center Norte (centro comercial): 9,3 km Aeropuertos más cercanos: São Paulo (GRU-Aeropuerto Internacional Guarulhos - Governador Andre Franco Montoro): 22,8 kmSão Paulo (CGH-Congonhas): 19,1 kmAeropuerto recomendado para Blue Tree Towers Anália Franco - Tatuapé: São Paulo (GRU-Aeropuerto Internacional Guarulhos - Governador Andre Franco Montoro). Si reservas tu estadía en Blue Tree Towers Anália Franco - Tatuapé, que se ubica en la zona de Zona Este, te encontrarás a pocos pasos de Parque deportivo Parque Esportivo dos Trabalhadores y a 7 a pie de Southern Cross University. Hospédate en este hotel de 4 estrellas y estarás a 0,8 km de Centro comercial Analia Franco, así como a 1 km de Hospital e Maternidade Vitória.En Sao Paulo (Zona Este)
", 4.3, 5, 4),
    ("Matiz Manhattan Hotel", "El Matiz Manhattan Hotel ofrece apartamentos de 1, 2 y 3 dormitorios que son amplios, ofrece también Wi-Fi, estacionamiento y desayuno gratuito, mini cocina, anti-baño, aire acondicionado, caja fuerte digital, TV LCD de pago en un ambiente moderno ideal para quienes viajan por trabajo o turismo.

Situado en el corazón del Barrio Jardins, a dos cuadras de la Avenida Paulista y de la estación de metro Consolação, ya 500 metros de la calle Oscar Freire, donde se ubican diversas tiendas de grifes nacionales e internacionales.

El área de ocio dispone de piscina descubierta, sauna y gimnasio.

El restaurante Francy's Natural, anexo al hotel, ofrece una alimentación sana y un menú variado.

Con un personal atento y acogedor el huésped experimentará excelentes experiencias en el Hotel Matiz Manhattan São Paulo.
", 3.6, 3, 3);

INSERT INTO `db_prod`.`imagenes` (`url`, `titulo`, `productos_id`)
VALUES 
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/1/1.jpeg", "imagen1", 1),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/1/2.jpeg", "imagen2", 1),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/1/3.jpeg", "imagen3", 1),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/1/4.jpeg", "imagen4", 1),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/1/5.jpeg", "imagen5", 1),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/2/1.jpeg", "imagen6", 2),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/2/2.jpeg", "imagen7", 2),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/2/3.jpeg", "imagen8", 2),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/2/4.jpeg", "imagen9", 2),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/2/5.jpeg", "imagen10", 2),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/3/1.jpeg", "imagen11", 3),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/3/2.jpeg", "imagen12", 3),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/3/3.jpeg", "imagen13", 3),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/3/4.jpeg", "imagen14", 3),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/3/5.jpeg", "imagen15", 3),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/4/1.jpeg", "imagen16", 4),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/4/2.jpeg", "imagen17", 4),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/4/3.jpeg", "imagen18", 4),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/4/4.jpeg", "imagen19", 4),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/4/5.jpeg", "imagen20", 4),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/5/1.jpeg", "imagen21", 5),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/5/2.jpeg", "imagen22", 5),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/5/3.jpeg", "imagen23", 5),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/5/4.jpeg", "imagen24", 5),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/5/5.jpeg", "imagen25", 5),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/6/1.jpeg", "imagen26", 6),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/6/2.jpeg", "imagen27", 6),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/6/3.jpeg", "imagen28", 6),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/6/4.jpeg", "imagen29", 6),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/6/5.jpeg", "imagen30", 6),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/7/1.jpeg", "imagen31", 7),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/7/2.jpeg", "imagen32", 7),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/7/3.jpeg", "imagen33", 7),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/7/4.jpeg", "imagen34", 7),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/7/5.jpeg", "imagen35", 7),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/8/1.jpeg", "imagen36", 8),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/8/2.jpeg", "imagen37", 8),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/8/3.jpeg", "imagen38", 8),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/8/4.jpeg", "imagen39", 8),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/8/5.jpeg", "imagen40", 8),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/9/1.jpeg", "imagen41", 9),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/9/2.jpeg", "imagen42", 9),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/9/3.jpeg", "imagen43", 9),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/9/4.jpeg", "imagen44", 9),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/9/5.jpeg", "imagen45", 9),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/10/1.jpeg", "imagen46", 10),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/10/2.jpeg", "imagen47", 10),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/10/3.jpeg", "imagen48", 10),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/10/4.jpeg", "imagen49", 10),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/10/5.jpeg", "imagen50", 10),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/11/1.jpeg", "imagen51", 11),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/11/2.jpeg", "imagen52", 11),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/11/3.jpeg", "imagen53", 11),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/11/4.jpeg", "imagen54", 11),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/11/5.jpeg", "imagen55", 11),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/12/1.jpeg", "imagen56", 12),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/12/2.jpeg", "imagen57", 12),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/12/3.jpeg", "imagen58", 12),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/12/4.jpeg", "imagen59", 12),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/12/5.jpeg", "imagen60", 12),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/13/1.jpeg", "imagen61", 13),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/13/2.jpeg", "imagen62", 13),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/13/3.jpeg", "imagen63", 13),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/13/4.jpeg", "imagen64", 13),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/13/5.jpeg", "imagen65", 13),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/14/1.jpeg", "imagen66", 14),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/14/2.jpeg", "imagen67", 14),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/14/3.jpeg", "imagen68", 14),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/14/4.jpeg", "imagen69", 14),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/14/5.jpeg", "imagen70", 14),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/15/1.jpeg", "imagen71", 15),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/16/1.jpeg", "imagen72", 16),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/16/2.jpeg", "imagen73", 16),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/16/3.jpeg", "imagen74", 16),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/16/4.jpeg", "imagen75", 16),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/16/5.jpeg", "imagen76", 16),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/17/1.jpeg", "imagen77", 17),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/17/2.jpeg", "imagen78", 17),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/17/3.jpeg", "imagen79", 17),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/17/4.jpeg", "imagen80", 17),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/17/5.jpeg", "imagen81", 17),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/18/1.jpeg", "imagen82", 18),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/18/2.jpeg", "imagen83", 18),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/18/3.jpeg", "imagen84", 18),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/18/4.jpeg", "imagen85", 18),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/18/5.jpeg", "imagen86", 18),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/19/1.jpeg", "imagen87", 19),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/19/2.jpeg", "imagen88", 19),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/19/3.jpeg", "imagen89", 19),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/19/4.jpeg", "imagen90", 19),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/19/5.jpeg", "imagen91", 19),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/20/1.jpeg", "imagen92", 20),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/20/2.jpeg", "imagen93", 20),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/20/3.jpeg", "imagen94", 20),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/20/4.jpeg", "imagen95", 20),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/20/5.jpeg", "imagen96", 20),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/21/1.jpeg", "imagen97", 21),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/21/2.jpeg", "imagen98", 21),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/21/3.jpeg", "imagen99", 21),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/21/4.jpeg", "imagen100", 21),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/21/5.jpeg", "imagen101", 21),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/22/1.jpeg", "imagen102", 22),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/22/2.jpeg", "imagen103", 22),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/22/3.jpeg", "imagen104", 22),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/22/4.jpeg", "imagen105", 22),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/22/5.jpeg", "imagen106", 22),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/23/1.jpeg", "imagen107", 23),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/23/2.jpeg", "imagen108", 23),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/23/3.jpeg", "imagen109", 23),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/23/4.jpeg", "imagen110", 23),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/23/5.jpeg", "imagen111", 23),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/24/1.jpeg", "imagen112", 24),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/24/2.jpeg", "imagen113", 24),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/24/3.jpeg", "imagen114", 24),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/24/4.jpeg", "imagen115", 24),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/24/5.jpeg", "imagen116", 24),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/25/1.jpeg", "imagen117", 25),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/25/2.jpeg", "imagen118", 25),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/25/3.jpeg", "imagen119", 25),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/25/4.jpeg", "imagen120", 25),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/25/5.jpeg", "imagen121", 25),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/26/1.jpeg", "imagen122", 26),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/26/2.jpeg", "imagen123", 26),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/26/3.jpeg", "imagen124", 26),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/26/4.jpeg", "imagen125", 26),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/26/5.jpeg", "imagen126", 26),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/27/1.jpeg", "imagen127", 27),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/27/2.jpeg", "imagen128", 27),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/27/3.jpeg", "imagen129", 27),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/27/4.jpeg", "imagen130", 27),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/27/5.jpeg", "imagen131", 27),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/28/1.jpeg", "imagen132", 28),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/28/2.jpeg", "imagen133", 28),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/28/3.jpeg", "imagen134", 28),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/28/4.jpeg", "imagen135", 28),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/28/5.jpeg", "imagen136", 28),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/29/1.jpeg", "imagen137", 29),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/29/2.jpeg", "imagen138", 29),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/29/3.jpeg", "imagen139", 29),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/29/4.jpeg", "imagen140", 29),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/29/5.jpeg", "imagen141", 29),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/30/1.jpeg", "imagen142", 30),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/30/2.jpeg", "imagen143", 30),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/30/3.jpeg", "imagen144", 30),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/30/4.jpeg", "imagen145", 30),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/30/5.jpeg", "imagen146", 30),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/31/1.jpeg", "imagen147", 31),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/31/2.jpeg", "imagen148", 31),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/31/3.jpeg", "imagen149", 31),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/31/4.jpeg", "imagen150", 31),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/31/5.jpeg", "imagen151", 31),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/32/1.jpeg", "imagen152", 32),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/32/2.jpeg", "imagen153", 32),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/32/3.jpeg", "imagen154", 32),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/32/4.jpeg", "imagen155", 32),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/32/5.jpeg", "imagen156", 32),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/33/1.jpeg", "imagen157", 33),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/33/2.jpeg", "imagen158", 33),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/33/3.jpeg", "imagen159", 33),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/33/4.jpeg", "imagen160", 33),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/33/5.jpeg", "imagen161", 33),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/34/1.jpeg", "imagen162", 34),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/34/2.jpeg", "imagen163", 34),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/34/3.jpeg", "imagen164", 34),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/34/4.jpeg", "imagen165", 34),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/34/5.jpeg", "imagen166", 34),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/35/1.jpeg", "imagen167", 35),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/35/2.jpeg", "imagen168", 35),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/35/3.jpeg", "imagen169", 35),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/35/4.jpeg", "imagen170", 35),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/35/5.jpeg", "imagen171", 35),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/36/1.jpeg", "imagen172", 36),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/36/2.jpeg", "imagen173", 36),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/36/3.jpeg", "imagen174", 36),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/36/4.jpeg", "imagen175", 36),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/36/5.jpeg", "imagen176", 36),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/37/1.jpeg", "imagen177", 37),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/37/2.jpeg", "imagen178", 37),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/37/3.jpeg", "imagen179", 37),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/37/4.jpeg", "imagen180", 37),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/37/5.jpeg", "imagen181", 37),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/38/1.jpeg", "imagen182", 38),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/38/2.jpeg", "imagen183", 38),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/38/3.jpeg", "imagen184", 38),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/38/4.jpeg", "imagen185", 38),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/38/5.jpeg", "imagen186", 38),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/39/1.jpeg", "imagen187", 39),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/39/2.jpeg", "imagen188", 39),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/39/3.jpeg", "imagen189", 39),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/39/4.jpeg", "imagen190", 39),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/39/5.jpeg", "imagen191", 39),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/40/1.jpeg", "imagen192", 40),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/40/2.jpeg", "imagen193", 40),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/40/3.jpeg", "imagen194", 40),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/40/4.jpeg", "imagen195", 40),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/40/5.jpeg", "imagen196", 40),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/41/1.jpeg", "imagen197", 41),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/41/2.jpeg", "imagen198", 41),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/41/3.jpeg", "imagen199", 41),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/41/4.jpeg", "imagen200", 41),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/41/5.jpeg", "imagen201", 41),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/42/1.jpeg", "imagen202", 42),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/42/2.jpeg", "imagen203", 42),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/42/3.jpeg", "imagen204", 42),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/42/4.jpeg", "imagen205", 42),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/42/5.jpeg", "imagen206", 42),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/43/1.jpeg", "imagen207", 43),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/43/2.jpeg", "imagen208", 43),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/43/3.jpeg", "imagen209", 43),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/43/4.jpeg", "imagen210", 43),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/43/5.jpeg", "imagen211", 43),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/44/1.jpeg", "imagen212", 44),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/44/2.jpeg", "imagen213", 44),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/44/3.jpeg", "imagen214", 44),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/44/4.jpeg", "imagen215", 44),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/44/5.jpeg", "imagen216", 44),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/45/1.jpeg", "imagen217", 45),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/45/2.jpeg", "imagen218", 45),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/45/3.jpeg", "imagen219", 45),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/45/4.jpeg", "imagen220", 45),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/45/5.jpeg", "imagen221", 45),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/46/1.jpeg", "imagen222", 46),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/46/2.jpeg", "imagen223", 46),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/46/3.jpeg", "imagen224", 46),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/46/4.jpeg", "imagen225", 46),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/46/5.jpeg", "imagen226", 46),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/47/1.jpeg", "imagen227", 47),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/47/2.jpeg", "imagen228", 47),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/47/3.jpeg", "imagen229", 47),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/47/4.jpeg", "imagen230", 47),
    ("https://barbudos-y-maga-g2.s3.amazonaws.com/images/47/5.jpeg", "imagen231", 47);

INSERT INTO `db_prod`.`caracteristicas_productos` (`caracteristicas_id`, `productos_id`)
VALUES
    (1, 1),
    (2, 1),
    (1, 2),
    (2, 2),
    (1, 3),
    (2, 3),
    (1, 4),
    (2, 4),
    (1, 5),
    (2, 5),
    (1, 6),
    (2, 6),
    (3, 6),
    (4, 6),
    (5, 6),
    (1, 7),
    (2, 7),
    (1, 8),
    (1, 9),
    (2, 9),
    (3, 9),
    (4, 9),
    (1, 10),
    (2, 10),
    (1, 11),
    (2, 11),
    (3, 11),
    (4, 11),
    (1, 12),
    (2, 12),
    (3, 12),
    (1, 13),
    (2, 13),
    (3, 13),
    (1, 14),
    (2, 14),
    (1, 15),
    (2, 15),
    (1, 17),
    (2, 17),
    (1, 18),
    (1, 19),
    (2, 19),
    (3, 19),
    (1, 20),
    (2, 20),
    (1, 21),
    (2, 21),
    (3, 21),
    (4, 21),
    (5, 21),
    (1, 22),
    (2, 22),
    (3, 22),
    (4, 22),
    (5, 22),
    (1, 23),
    (2, 23),
    (3, 23),
    (4, 23),
    (1, 24),
    (1, 25),
    (2, 25),
    (1, 26),
    (1, 27),
    (2, 27),
    (1, 29),
    (1, 30),
    (2, 30),
    (3, 30),
    (4, 30),
    (1, 31),
    (1, 33),
    (1, 34),
    (2, 34),
    (1, 35),
    (2, 35),
    (3, 35),
    (4, 35),
    (1, 36),
    (2, 36),
    (3, 36),
    (4, 36),
    (1, 38),
    (2, 38),
    (3, 38),
    (1, 39),
    (2, 39),
    (1, 40),
    (2, 40),
    (3, 40),
    (1, 41),
    (1, 42),
    (2, 42),
    (1, 44),
    (2, 44),
    (1, 46),
    (2, 46),
    (1, 47),
    (2, 47);

INSERT INTO `db_prod`.`roles` (`id`, `name`)
VALUES 
    (1, "ADMIN"),
    (2, "USER");

INSERT INTO `db_prod`.`usuarios` (`id`, `first_name`, `last_name`, `email`, `password`, `roles_id`, `active`)
VALUES
	(1, 'Adrian', 'Araoz', 'aa@email.com', '$2a$10$694IwwxOaVPqXy7tmxBgfuiMzdrDW6JPsx/yRCqWXmFtLkTuevmrW', 1, TRUE),
	(2, 'Belen', 'Buzio', 'bb@email.com', '$2a$10$5I2nv3oEA6jlVz.7BoYxduwm9N54Z1.TQek5YDGqef6Sp4ehEkqbK', 2, TRUE),
	(3, 'Cristian', 'Castro', 'cc@email.com', '$2a$10$mtSI6R1iPlPvI8CY6VRec.xE3faiOm356xAHy2GW0qLslFdjK1XCG', 2, TRUE);


INSERT INTO `db_prod`.`tipo_politicas` (`name`)
VALUES
    ("Normas de la casa"),
    ("Salud y seguridad"),
    ("Política de cancelacion");

INSERT INTO `db_prod`.`politicas` (`tipo_politicas_id`, `name`)
VALUES
    (1, "Check-out:10AM"),
    (1, "No se permiten fiestas"),
    (1, "No fumar"),
    (2, "Cerrar la casa"),
    (2, "Se requiere certificado de vacunacion de covid"),
    (3, "Un deposito con la mitad del valor de la estadia"),
    (3, "Debera cancelar con sesenta(60) dias de anticipacion");

INSERT INTO `db_prod`.`politicas_productos` (`productos_id`, `politicas_id`)
VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (1, 4),
    (1, 5),
    (1, 6),
    (1, 7),
    (2, 1),
    (2, 2),
    (2, 3),
    (2, 4),
    (2, 5),
    (2, 6),
    (2, 7),
    (3, 1),
    (3, 2),
    (3, 3),
    (3, 4),
    (3, 5),
    (3, 6),
    (3, 7),
    (4, 1),
    (4, 2),
    (4, 3),
    (4, 4),
    (4, 5),
    (4, 6),
    (4, 7),
    (5, 1),
    (5, 2),
    (5, 3),
    (5, 4),
    (5, 5),
    (5, 6),
    (5, 7),
    (6, 1),
    (6, 2),
    (6, 3),
    (6, 4),
    (6, 5),
    (6, 6),
    (6, 7),
    (7, 1),
    (7, 2),
    (7, 3),
    (7, 4),
    (7, 5),
    (7, 6),
    (7, 7),
    (8, 1),
    (8, 2),
    (8, 3),
    (8, 4),
    (8, 5),
    (8, 6),
    (8, 7),
    (9, 1),
    (9, 2),
    (9, 3),
    (9, 4),
    (9, 5),
    (9, 6),
    (9, 7),
    (10, 1),
    (10, 2),
    (10, 3),
    (10, 4),
    (10, 5),
    (10, 6),
    (10, 7),
    (11, 1),
    (11, 2),
    (11, 3),
    (11, 4),
    (11, 5),
    (11, 6),
    (11, 7),
    (12, 1),
    (12, 2),
    (12, 3),
    (12, 4),
    (12, 5),
    (12, 6),
    (12, 7),
    (13, 1),
    (13, 2),
    (13, 3),
    (13, 4),
    (13, 5),
    (13, 6),
    (13, 7),
    (14, 1),
    (14, 2),
    (14, 3),
    (14, 4),
    (14, 5),
    (14, 6),
    (14, 7),
    (15, 1),
    (15, 2),
    (15, 3),
    (15, 4),
    (15, 5),
    (15, 6),
    (15, 7),
    (16, 1),
    (16, 2),
    (16, 3),
    (16, 4),
    (16, 5),
    (16, 6),
    (16, 7),
    (17, 1),
    (17, 2),
    (17, 3),
    (17, 4),
    (17, 5),
    (17, 6),
    (17, 7),
    (18, 1),
    (18, 2),
    (18, 3),
    (18, 4),
    (18, 5),
    (18, 6),
    (18, 7),
    (19, 1),
    (19, 2),
    (19, 3),
    (19, 4),
    (19, 5),
    (19, 6),
    (19, 7),
    (20, 1),
    (20, 2),
    (20, 3),
    (20, 4),
    (20, 5),
    (20, 6),
    (20, 7),
    (21, 1),
    (21, 2),
    (21, 3),
    (21, 4),
    (21, 5),
    (21, 6),
    (21, 7),
    (22, 1),
    (22, 2),
    (22, 3),
    (22, 4),
    (22, 5),
    (22, 6),
    (22, 7),
    (23, 1),
    (23, 2),
    (23, 3),
    (23, 4),
    (23, 5),
    (23, 6),
    (23, 7),
    (24, 1),
    (24, 2),
    (24, 3),
    (24, 4),
    (24, 5),
    (24, 6),
    (24, 7),
    (25, 1),
    (25, 2),
    (25, 3),
    (25, 4),
    (25, 5),
    (25, 6),
    (25, 7),
    (26, 1),
    (26, 2),
    (26, 3),
    (26, 4),
    (26, 5),
    (26, 6),
    (26, 7),
    (27, 1),
    (27, 2),
    (27, 3),
    (27, 4),
    (27, 5),
    (27, 6),
    (27, 7),
    (28, 1),
    (28, 2),
    (28, 3),
    (28, 4),
    (28, 5),
    (28, 6),
    (28, 7),
    (29, 1),
    (29, 2),
    (29, 3),
    (29, 4),
    (29, 5),
    (29, 6),
    (29, 7),
    (30, 1),
    (30, 2),
    (30, 3),
    (30, 4),
    (30, 5),
    (30, 6),
    (30, 7),
    (31, 1),
    (31, 2),
    (31, 3),
    (31, 4),
    (31, 5),
    (31, 6),
    (31, 7),
    (32, 1),
    (32, 2),
    (32, 3),
    (32, 4),
    (32, 5),
    (32, 6),
    (32, 7),
    (33, 1),
    (33, 2),
    (33, 3),
    (33, 4),
    (33, 5),
    (33, 6),
    (33, 7),
    (34, 1),
    (34, 2),
    (34, 3),
    (34, 4),
    (34, 5),
    (34, 6),
    (34, 7),
    (35, 1),
    (35, 2),
    (35, 3),
    (35, 4),
    (35, 5),
    (35, 6),
    (35, 7),
    (36, 1),
    (36, 2),
    (36, 3),
    (36, 4),
    (36, 5),
    (36, 6),
    (36, 7),
    (37, 1),
    (37, 2),
    (37, 3),
    (37, 4),
    (37, 5),
    (37, 6),
    (37, 7),
    (38, 1),
    (38, 2),
    (38, 3),
    (38, 4),
    (38, 5),
    (38, 6),
    (38, 7),
    (39, 1),
    (39, 2),
    (39, 3),
    (39, 4),
    (39, 5),
    (39, 6),
    (39, 7),
    (40, 1),
    (40, 2),
    (40, 3),
    (40, 4),
    (40, 5),
    (40, 6),
    (40, 7),
    (41, 1),
    (41, 2),
    (41, 3),
    (41, 4),
    (41, 5),
    (41, 6),
    (41, 7),
    (42, 1),
    (42, 2),
    (42, 3),
    (42, 4),
    (42, 5),
    (42, 6),
    (42, 7),
    (43, 1),
    (43, 2),
    (43, 3),
    (43, 4),
    (43, 5),
    (43, 6),
    (43, 7),
    (44, 1),
    (44, 2),
    (44, 3),
    (44, 4),
    (44, 5),
    (44, 6),
    (44, 7),
    (45, 1),
    (45, 2),
    (45, 3),
    (45, 4),
    (45, 5),
    (45, 6),
    (45, 7),
    (46, 1),
    (46, 2),
    (46, 3),
    (46, 4),
    (46, 5),
    (46, 6),
    (46, 7),
    (47, 1),
    (47, 2),
    (47, 3),
    (47, 4),
    (47, 5),
    (47, 6),
    (47, 7);

