version: '3'
services:
  playground-web-frontend:
    image: playground-web-frontend:latest
    environment:
      - PORT=80
      - REACT_APP_API_ENDPOINT=http://ec2-34-207-66-248.compute-1.amazonaws.com:8080
      - NODE_APP_API_ENDPOINT=http://ec2-34-207-66-248.compute-1.amazonaws.com:8080
    ports:
      - 80:80
  playground-web-backend:
    image: playground-web-backend:latest
    environment:
      - MYSQL_DATABASE_URL=jdbc:mysql://barbudosymaga-grupo-02.ckiqtgesdyez.us-east-1.rds.amazonaws.com:3306/db_prod?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    networks:
            - spring-cloud-network
    ports:
      - 8080:8080
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
networks:
    spring-cloud-network:
        driver: bridge
